/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{html,js,jsx,css}"],

  theme: {
    extend: {
      colors: {
        primary: "orange",
        secondary: "#060d17",
        dark: "black",
        light: "white",
        "pale-white": "#FFFFFF90",
        "pri-dark": "#0a151f",
        gray: "#1c252f",
        green: "#00cc66",
        red: "#ff5050",
        yellow: "#ffcc00",
        "blue-purple": "#6699ff",
        "green-dark": "#1abc9c",
      },
      backgroundColor: {
        primary: "orange",
        secondary: "#060d17",
        dark: "black",
        light: "white",
        "gray-transparent": "#0009",
        green: "#00cc66",
        "green-dark": "#1abc9c",
        red: "#ff5050",
        "pale-white": "#FFFFFF90",
        loading: "bg-slate-800",
        "pri-dark": "#0a151f",
        gray: "#1c252f",
        input: "#eee",
        "green-light": "#caffbf",
        "red-light": "#ffadad",
        "yellow-light": "#fdffb6",
        "orange-light": "#ffd6a5",
        "blue-light": "#9bf6ff",
        "blue-dark": "#a0c4ff",
        pink: "#ffc6ff",
        purple: "#bdb2ff",
      },
      borderColor: {
        primary: "orange",
        secondary: "#060d17",
        dark: "black",
        light: "white",
        "pale-white": "#FFFFFF90",
        "pri-dark": "#0a151f",
        gray: "#1c252f",
        green: "#00cc66",
        red: "#ff5050",
      },
      fontSize: {
        xsm: "10px",
        sm11: "11px",
        sm: "12px",
        smd: "13px",
        sm14: "14px",
        md: "15px",
        lg: "18px",
        lg21: "21px",
        xl: "22px",
        xl24: "24px",
        xml: "28px",
        xxl: "30px",
        xxl40: "40px",
        xxx: "50px",
      },
      fontWeight: {
        thin: 300,
        md: 500,
        mdbold: 600,
        bold: 700,
      },
      fontFamily: {
        primary: `"Nunito", sans-serif`,
      },
      backgroundImage: {
        "bg-image": "linear-gradient(0deg, #060d17, transparent 120px)",
      },
      animation: {
        opacity: "opacity 2s ease-in-out",
        opacityTrailer: "opacity 4s ease-in-out",
        alert: "alert 0.5s ease-in-out",
        "spin-border": "spin-border 1s ease-in-out",
        "show-edit": "show-edit 1s ease-in-out",
        "show-input": "show-input 1s ease-in-out",
      },
      keyframes: {
        opacity: {
          "0%": { opacity: 0 },
          "100%": { opacity: 1 },
        },
        opacityTrailer: {
          "0%": { opacity: 0 },
          "100%": { opacity: 1 },
        },
        alert: {
          "0%": { bottom: "-100px", opacity: 0 },
          "100%": { bottom: "15px", opacity: 1 },
        },
        "spin-border": {
          "0%": { strokeDashoffset: 0, stroke: "#1abc9c" },
          "100%": { strokeDashoffset: -380, stroke: "#1abc9c" },
        },
        "show-edit": {
          "0%": { width: "0px", fontSize: "0px" },
          "100%": { width: "120px", fontSize: "13px" },
        },
        "show-input": {
          "0%": { width: "10px", fontSize: "14px" },
          "100%": { width: "200px", fontSize: "14px" },
        },
      },
    },
  },
  plugins: [],
};
